//
//  File.swift
//  WisataApp
//
//  Created by KhalishTianto User on 06/04/21.
//

var Data = [

    destination(id: 0, image: "ap", namawisata: "Bromo Mountain", namatempat: "Malang, Jakarta Timur", rating: 5, jarak: "91km", jam: "Buka Jam 05.00", tempattujuan: "Gn. Bromo, Area Gn. Bromo, Podokoyo, Tosari, Pasuruan, Jawa Timur", guide: "Tersedia Tour Guide", description: """
        Gunung Bromo (dari bahasa Sanskerta: Brahma, salah seorang Dewa Utama dalam agama Hindu) atau dalam bahasa Tengger dieja "Brama", adalah sebuah gunung berapi aktif di Jawa Timur, Indonesia. Gunung ini memiliki ketinggian 2.329 meter di atas permukaan laut dan berada dalam empat wilayah kabupaten, yakni Kabupaten Probolinggo, Kabupaten Pasuruan, Kabupaten Lumajang, dan Kabupaten Malang. Gunung Bromo terkenal sebagai objek wisata utama di Jawa Timur. Sebagai sebuah objek wisata, Bromo menjadi menarik karena statusnya sebagai gunung berapi yang masih aktif. Gunung Bromo termasuk dalam kawasan Taman Nasional Bromo Tengger Semeru.
                
        Bentuk tubuh Gunung Bromo bertautan antara lembah dan ngarai dengan kaldera atau lautan pasir seluas sekitar 10 kilometer persegi. Ia mempunyai sebuah kawah dengan garis tengah ± 800 meter (utara-selatan) dan ± 600 meter (timur-barat). Sedangkan daerah bahayanya berupa lingkaran dengan jari-jari 4 km dari pusat kawah Bromo.
"""),
    destination(id: 1, image: "candi", namawisata: "Candi Borobudur", namatempat: "Jawa Tengah", rating: 5, jarak: "102km", jam: "Buka jam 06:00", tempattujuan: "Candi Borobudur, Jl. Badrawati, Kw. Candi Borobudur, Borobudur, Kec. Borobudur, Magelang, Jawa Tengah", guide: "Tersedia Tour Guide", description: """
        Borobudur (bahasa Jawa: ꦕꦤ꧀ꦝꦶ​ꦧꦫꦧꦸꦝꦸꦂ, translit. Candhi Barabudhur) adalah sebuah candi Buddha yang terletak di Borobudur, Magelang, Jawa Tengah, Indonesia. Candi ini terletak kurang lebih 100 km di sebelah barat daya Semarang, 86 km di sebelah barat Surakarta, dan 40 km di sebelah barat laut Yogyakarta. Candi berbentuk stupa ini didirikan oleh para penganut agama Buddha Mahayana sekitar tahun 800-an Masehi pada masa pemerintahan wangsa Syailendra. Borobudur adalah candi atau kuil Buddha terbesar di dunia[1][2], sekaligus salah satu monumen Buddha terbesar di dunia[3].
                
        Monumen ini terdiri atas enam teras berbentuk bujur sangkar yang di atasnya terdapat tiga pelataran melingkar, pada dindingnya dihiasi dengan 2.672 panel relief dan aslinya terdapat 504 arca Buddha[4]. Borobudur memiliki koleksi relief Buddha terlengkap dan terbanyak di dunia[3]. Stupa utama terbesar teletak di tengah sekaligus memahkotai bangunan ini, dikelilingi oleh tiga barisan melingkar 72 stupa berlubang yang di dalamnya terdapat arca Buddha tengah duduk bersila dalam posisi teratai sempurna dengan mudra (sikap tangan) Dharmachakra mudra (memutar roda dharma).

        Monumen ini merupakan model alam semesta dan dibangun sebagai tempat suci untuk memuliakan Buddha sekaligus berfungsi sebagai tempat ziarah untuk menuntun umat manusia beralih dari alam nafsu duniawi menuju pencerahan dan kebijaksanaan sesuai ajaran Buddha.[5] Para peziarah masuk melalui sisi timur dan memulai ritual di dasar candi dengan berjalan melingkari bangunan suci ini searah jarum jam, sambil terus naik ke undakan berikutnya melalui tiga tingkatan ranah dalam kosmologi Buddha. Ketiga tingkatan itu adalah Kāmadhātu (ranah hawa nafsu), Rupadhatu (ranah berwujud), dan Arupadhatu (ranah tak berwujud). Dalam perjalanannya para peziarah berjalan melalui serangkaian lorong dan tangga dengan menyaksikan tak kurang dari 1.460 panel relief indah yang terukir pada dinding dan pagar langkan.

        Menurut bukti-bukti sejarah, Borobudur ditinggalkan pada abad ke-14 seiring melemahnya pengaruh kerajaan Hindu dan Buddha di Jawa serta mulai masuknya pengaruh Islam.[6] Dunia mulai menyadari keberadaan bangunan ini sejak ditemukan 1814 oleh Sir Thomas Stamford Raffles, yang saat itu menjabat sebagai Gubernur Jenderal Inggris atas Jawa. Sejak saat itu Borobudur telah mengalami serangkaian upaya penyelamatan dan pemugaran (perbaikan kembali). Proyek pemugaran terbesar digelar pada kurun waktu 1975 hingga 1982 atas upaya Pemerintah Republik Indonesia dan UNESCO, kemudian situs bersejarah ini masuk dalam daftar Situs Warisan Dunia.[3]

        Borobudur kini masih digunakan sebagai tempat ziarah keagamaan; tiap tahun umat Buddha yang datang dari seluruh Indonesia dan mancanegara berkumpul di Borobudur untuk memperingati Trisuci Waisak. Dalam dunia pariwisata, Borobudur adalah objek wisata tunggal di Indonesia yang paling banyak dikunjungi wisatawan.
"""),
    destination(id: 2, image: "toba", namawisata: "Danau Toba", namatempat: "Sumatra Utara", rating: 5, jarak: "34km", jam: "Buka jam 06:00", tempattujuan: "Danau Toba, Sumatera Utara", guide: "Tersedia Tour Guide", description: """
        Danau Toba (Aksara Batak Toba : ᯖᯆᯬᯖᯬᯅ, translit. Tao Toba) adalah danau alami berukuran besar di Indonesia yang berada di kaldera Gunung Supervulkan. Danau ini memiliki panjang 100 kilometer (62 mil), lebar 30 kilometer (19 mi), dan kedalaman 505 meter (1657 ft). Danau ini terletak di tengah pulau Sumatra bagian utara dengan ketinggian permukaan sekitar 900 meter (2953 ft). Danau ini membentang dari 2.88°N 98.52°E sampai 2.35°N 99.1°E. Ini adalah danau terbesar di Indonesia dan danau vulkanik terbesar di dunia.[1]
                
        Danau Toba adalah lokasi letusan gunung berapi super masif berkekuatan VEI 8 sekitar 69.000 sampai 77.000 tahun yang lalu[2][3][4] yang memicu perubahan iklim global. Metode penanggalan terkini menetapkan bahwa 74.000 tahun yang lalu lebih akurat.[5] Letusan ini merupakan letusan eksplosif terbesar di Bumi dalam kurun 25 juta tahun terakhir. Menurut teori bencana Toba, letusan ini berdampak besar bagi populasi manusia di seluruh dunia; dampak letusan menewaskan sebagian besar manusia yang hidup waktu itu dan diyakini menyebabkan penyusutan populasi di Afrika timur tengah dan India sehingga memengaruhi genetika populasi manusia di seluruh dunia sampai sekarang.[6]

        Para ilmuwan sepakat bahwa letusan Toba memicu musim dingin vulkanik yang menyebabkan jatuhnya suhu dunia antara 3 hingga 5 °C (5,4 hingga 9,0 °F), dan hingga 15 °C (27 °F) di daerah lintang atas. Penelitian lanjutan di Danau Malawi, Afrika Tengah, menemukan endapan debu letusan Toba, tetapi tidak menemukan bukti perubahan iklim besar di Afrika Timur.[7] Pada tanggal 18 Juni 2018, musibah tenggelamnya kapal feri terjadi di Danau Toba dan menenggelamkan lebih dari 190 orang.[8]

        Ada juga tempat wisata yang terkenal yaitu wisata air rangat tepatnya di bawah kaki gunung pusuk buhit, air rangat itu adalah air hangat yang berasal dari gunung yang meletus dan Pusuk Buhit sendiri adalah sebuah gunung aktif yang sangat disakralkan oleh etnis Batak sehingga beragam cerita mistis pun terdapat di gunung ini. Gunung ini terletak di Pulau Samosir, dan merupakan puncak tertinggi dari semua dataran tinggi di Pulau Samosir. Dengan ketinggian sekitar 1.077 meter dari Danau Toba, gunung ini terlihat berdiri dengan gagahnya. Sehingga apabila Anda sedang berada di sekitar perairan Danau Toba, maka Gunung Pusuk Buhit ini akan terlihat sangat jelas sekali dengan puncaknya yang berwarna hijau dengan kombinasi warna abu-abu dan ditutupi oleh awan di sekitarnya. Lalu ketika kita berenang di air rangat itu tidak membayar uang masuk, tinggal masuk saja tapi setelah kita selesai mandi atau selesai berenang kita diharuskan makan di tempat permandian air rangat.
"""),
    destination(id: 3, image: "komodo", namawisata: "Pulau Komodo", namatempat: "Nusa Tenggara Timur", rating: 5, jarak: "52km", jam: "Buka Jam 10:00", tempattujuan: "Pulau Komodo, Komodo, Kabupaten Manggarai Barat, Nusa Tenggara Tim.", guide: "Tersedia Tour Guide", description: """
        Pulau Komodo adalah sebuah pulau yang terletak di Kepulauan Nusa Tenggara, berada di sebelah timur Pulau Sumbawa, yang dipisahkan oleh Selat Sape. Pulau Komodo dikenal sebagai habitat asli hewan komodo.
                
        Pulau ini termasuk salah satu kawasan Taman Nasional Komodo yang dikelola oleh Pemerintah Pusat.

        Secara administratif, pulau ini termasuk wilayah Kabupaten Manggarai Barat, Kecamatan Komodo, Provinsi Nusa Tenggara Timur, Indonesia. Pulau Komodo merupakan ujung paling barat Provinsi Nusa Tenggara Timur, berbatasan dengan Provinsi Nusa Tenggara Barat.

        Di Pulau Komodo, hewan komodo hidup dan berkembang biak dengan baik. Hingga Agustus 2009, di pulau ini terdapat sekitar 1300 ekor komodo. Ditambah dengan pulau lain, seperti Pulau Rinca dan dan Gili Motang, jumlah mereka keseluruhan mencapai sekitar 2500 ekor. Ada pula sekitar 100 ekor komodo di Cagar Alam Wae Wuul di daratan Pulau Flores tapi tidak termasuk wilayah Taman Nasional Komodo.

        Selain komodo, pulau ini juga menyimpan eksotisme flora yang beragam kayu sepang yang oleh warga sekitar digunakan sebagi obat dan bahan pewarna pakaian, pohon nitak ini atau sterculia oblongata di yakini berguna sebagai obat dan bijinya gurih dan enak seperti kacang polong.

        Pulau Komodo juga diterima sebagai Situs Warisan Dunia UNESCO, karena dalam wilayah Taman Nasional Komodo, bersama dengan Pulau Rinca, Pulau Padar dan Gili Motang
        """),
    destination(id: 4, image: "wakatobi", namawisata: "Wakatobi", namatempat: "Sulawesi Tenggara", rating: 5, jarak: "66km", jam: "Buka Jam 09:00", tempattujuan: "Jakarta, Daerah Khusus Ibukota Jakarta, Taman Nasional Wakatobi, Sulawesi Tenggara", guide: "Tidak Tersedia Tour Guide", description: """
        Kabupaten Wakatobi adalah salah satu kabupaten di Provinsi Sulawesi Tenggara, Indonesia. Ibu kota kabupaten ini terletak di Wangi-Wangi, dibentuk berdasarkan Undang-undang Republik Indonesia Nomor 29 Tahun 2003, tanggal 18 Desember 2003. Luas wilayahnya adalah 823 km² dan pada tahun 2011 berpenduduk 94.846 jiwa.
                
        Wakatobi juga merupakan nama kawasan taman nasional yang ditetapkan pada tahun 1996, dengan luas keseluruhan 1,39 juta hektare, menyangkut keanekaragaman hayati laut, skala dan kondisi karang yang menempati salah satu posisi prioritas tertinggi dari konservasi laut di Indonesia.
"""),
    destination(id: 5, image: "gili", namawisata: "Gili Trawangan", namatempat: "Nusa Tenggara Barat", rating: 5, jarak: "88km", jam: "Buka Jam 13:00", tempattujuan: "Kepulauan Gili, Gili Indah, Pemenang, Kabupaten Lombok Utara, Nusa Tenggara Bar.", guide: "Tersedia Tour Guide", description: """
        Kepulauan Gili atau Tiga Gili adalah kepulauan yang terdiri dari tiga pulau kecil atau pulau Gili kembar tiga[1] — Gili Trawangan, Gili Meno, dan Gili Air — tepat di lepas pantai barat laut Lombok, Indonesia.
                
        Kepulauan ini merupakan destinasi wisata populer bagi wisatawan. Setiap pulau memiliki beberapa sanggraloka kecil, biasanya terdiri dari kumpulan pondok untuk wisatawan, kolam kecil, dan restoran. Sebagian besar penduduk lokal tinggal di Trawangan di kota yang membentang di sepanjang sisi timurnya di pedalaman (yang juga merupakan tempat di mana perkembangan terakhir terjadi). Lalu lintas mobil dan kendaraan bermotor dilarang di kepulauan ini oleh peraturan setempat, dengan demikian metode transportasi yang disukai adalah dengan berjalan kaki dan bersepeda atau kereta yang ditarik kuda yang disebut cidomo. Penyelaman skuba dan bebas di dan sekitar Kepulauan Gili juga populer karena berlimpahnya kehidupan laut dan formasi karang yang menarik. Tempat menyelam yang paling terkenal adalah titik Hiu, titik Manta, dan karang Simon.
"""),
    destination(id: 6, image: "kelimutu", namawisata: "Danau Kelimutu", namatempat: "Nusa Tenggara Timur", rating: 5, jarak: "72km", jam: "Buka Jam 09:00", tempattujuan: "Gn. Kelimutu, Woloara, Kelimutu, Kabupaten Ende, Nusa Tenggara Tim.", guide: "Tersedia Tour Guide", description: """
        Gunung Kelimutu adalah gunung berapi yang terletak di Pulau Flores, Provinsi NTT, Indonesia. Lokasi gunung ini tepatnya di Desa Pemo, Kecamatan Kelimutu, Kabupaten Ende. Gunung ini memiliki tiga buah danau kawah di puncaknya. Danau ini dikenal dengan nama Danau Tiga Warna karena memiliki tiga warna yang berbeda, yaitu merah, biru, dan putih. Walaupun begitu, warna-warna tersebut selalu berubah-ubah seiring dengan perjalanan waktu.
                
        Kelimutu merupakan gabungan kata dari "keli" yang berarti gunung dan kata "mutu" yang berarti mendidih. Menurut kepercayaan penduduk setempat, warna-warna pada danau Kelimutu memiliki arti masing-masing dan memiliki kekuatan alam yang sangat dahsyat.

        Danau atau Tiwu Kelimutu di bagi atas tiga bagian yang sesuai dengan warna - warna yang ada di dalam danau. Danau berwarna biru atau "Tiwu Nuwa Muri Koo Fai" merupakan tempat berkumpulnya jiwa-jiwa muda-mudi yang telah meninggal. Danau yang berwarna merah atau "Tiwu Ata Polo" merupakan tempat berkumpulnya jiwa-jiwa orang yang telah meninggal dan selama ia hidup selalu melakukan kejahatan/tenung. Sedangkan danau berwarna putih atau "Tiwu Ata Mbupu" merupakan tempat berkumpulnya jiwa-jiwa orang tua yang telah meninggal.

        Para penduduk di sekitar Danau Kelimutu percaya, bahwa pada saat danau berubah warna, mereka harus memberikan sesajen bagi arwah orang - orang yang telah meninggal.

        Luas ketiga danau itu sekitar 1.051.000 meter persegi dengan volume air 1.292 juta meter kubik. Batas antar danau adalah dinding batu sempit yang mudah longsor. Dinding ini sangat terjal dengan sudut kemiringan 70 derajat. Ketinggian dinding danau berkisar antara 50 sampai 150 meter.
"""),
    destination(id: 7, image: "kawah", namawisata: "Kawah Ijen", namatempat: "Jawa Timur", rating: 5, jarak: "29km", jam: "Buka Jam 07:00", tempattujuan: "Gn. Ijen, Jawa Timur", guide: "Tersedia Tour Guide", description: """
        Gunung Ijen adalah sebuah gunung berapi yang terletak di perbatasan antara Kabupaten Banyuwangi dan Kabupaten Bondowoso, Jawa Timur, Indonesia. Gunung ini memiliki ketinggian 2.386 mdpl dan terletak berdampingan dengan Gunung Merapi. Gunung Ijen terakhir meletus pada tahun 1999. Salah satu fenomena alam yang paling terkenal dari Gunung Ijen adalah blue fire (api biru) di dalam kawah yang terletak di puncaknya. Pendakian gunung ini bisa dimulai dari dua tempat. Pendaki bisa berangkat dari Banyuwangi ataupun dari Bondowoso.
"""),
    destination(id: 8, image: "anambas", namawisata: "Kepulauan Anambas", namatempat: "Kepulauan Riau", rating: 5, jarak: "14km", jam: "Buka Jam 08:00", tempattujuan: "Kepulauan Anambas, Jemaja, Kabupaten Kepulauan Anambas, Kepulauan Riau", guide: "Tidak Tersedia Tour Guide", description: "Kabupaten Kepulauan Anambas adalah sebuah kabupaten di Provinsi Kepulauan Riau, Indonesia. Ibu kotanya adalah Tarempa. Kabupaten ini dibentuk berdasarkan Undang-Undang Nomor 33 Tahun 2008 yang merupakan pemekaran dari Kabupaten Natuna"),
    destination(id: 9, image: "ngarai", namawisata: "Ngarai Sianok", namatempat: "Bukit Tinggi", rating: 5, jarak: "46km", jam: "Buka Jam 06:00", tempattujuan: "Ngarai Sianok, BSD Sektor XII Blok K No. 12B Jl. Kencana Loka, Rw. Buntu, Kec. Serpong, Kota Tangerang Selatan, Banten 15157", guide: "Tersedia Tour Guide", description: """
        Ngarai Sianok adalah sebuah lembah curam (jurang) yang terletak di perbatasan kota Bukittinggi, di kecamatan IV Koto, Kabupaten Agam, Sumatra Barat. Lembah ini memanjang dan berkelok sebagai garis batas kota dari selatan ngarai Koto Gadang sampai ke nagari Sianok Anam Suku, dan berakhir di kecamatan Palupuh. Ngarai Sianok memiliki pemandangan yang sangat indah dan juga menjadi salah satu objek wisata andalan provinsi.
                
        Ngarai Sianok yang dalam jurangnya sekitar 100 m ini, membentang sepanjang 15 km dengan lebar sekitar 200 m, dan merupakan bagian dari patahan yang memisahkan pulau Sumatra menjadi dua bagian memanjang (patahan Semangko). Patahan ini membentuk dinding yang curam, bahkan tegak lurus dan membentuk lembah yang hijau—hasil dari gerakan turun kulit bumi (sinklinal)—yang dialiri Batang Sianok (batang berarti sungai, dalam bahasa Minangkabau) yang airnya jernih. Di zaman kolonial Belanda, jurang ini disebut juga sebagai karbouwengat atau kerbau sanget, karena banyaknya kerbau liar yang hidup bebas di dasar ngarai ini.

        Batang Sianok kini bisa diarungi dengan menggunakan kano dan kayak yang disaranai oleh suatu organisasi olahraga air "Qurays". Rute yang ditempuh adalah dari nagari Lambah sampai jorong Sitingkai nagari Palupuh selama kira-kira 3,5 jam. Di tepiannya masih banyak dijumpai tumbuhan langka seperti rafflesia dan tumbuhan obat-obatan. Fauna yang dijumpai misalnya monyet ekor panjang, siamang, simpai, rusa, babi hutan, macan tutul, dan juga tapir.
""")
]

